### ISSUE TITLE
Newest update 4.11.0 broke most remaining SC functions

### ISSUE THREAD

**Issue by nlof** [eljeffeg/SmartCopy#127]
The newest update (#124) has broken most previously remaining SC functions, see discussion starting on page 114 here: [https://www.geni.com/discussions/145968?msg=1715744&page=114](https://www.geni.com/discussions/145968?msg=1715744&page=114)

Among them: 
1) It is difficult to authorize SC in Geni and SC gets randomly disconnected from it
2) profile info is pulled much slower than before 
3) frequently the process just gets stuck in the "Reading Family Data..." which spins endlessly and the SC pop-up table never shows up. This reportedly happens on most sites (Ancestry and regular MH profiles which were already broken previously)  but also sites that worked previously (FamilySearch, FindAGrave, Wikitree and MH RecordMatch/SmartMatch).
4) children are ignored in the cases in which point 3 above doesn't happen. 

Other relevant stuff:

- Some have asked whether it is possible to roll back to the prior semi-functioning version.
- Please follow the [thread on Geni](https://www.geni.com/discussions/145968?msg=1715744&page=114) for additional details and issues.

Thank you all for your hard work.

When inspecting the extension in my browser and I click on "Errors" this pops up as the most frequent recurrent problem:
![Extensions](https://github.com/user-attachments/assets/f07dc0c0-fcc4-4476-8888-5edaaa5c5e42)

**Comment by nlof** [comment]
Version 4.11.0.1 seems to have solved at least part of the issues of the ill-fated v. 4.11.0 update so we regained some of the previous functionality.
Thank you!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
https://github.com/eljeffeg/SmartCopy/commit/e6f5eea67b7560aed274df0038646a744b075c33

**Comment by eljeffeg** [comment]
We had a 4.11.1 but it got rejected by Google for some reason. Working out those issues.
