### ISSUE TITLE
FamilySearch.org - not working after match

### ISSUE THREAD

**Issue by GuyKh** [eljeffeg/SmartCopy#128]
After matching - getting family members breaks the match

https://github.com/eljeffeg/SmartCopy/blob/master/collections/familysearchjson.js#L236

e.g. for profile: https://www.familysearch.org/tree/person/details/GTGD-K7Z 
It tries to call https://www.familysearch.org/service/tree/tree-data/family-members/person/GTGD-K7Z?includePhotos=true&locale=en

where it gets a response of:
```
{
    "type": "about:blank",
    "title": "Not Found",
    "status": 404,
    "detail": "No static resource family-members/person/GTGD-K7Z.",
    "instance": "/family-members/person/GTGD-K7Z"
}
```

A) Need to fix the problem (not sure where this URL is coming from but perhaps it's out of date
B) Need to avoid breaking the match in case of family-members failure

**Comment by GuyKh** [comment]
Looks like this is the relevant URL:
https://www.familysearch.org/service/tree/tree-data/r9/family-members/person/GRM9-HD3?includePhotos=true&treeId=PRIVATE

I wonder what is the `r9`

**Comment by eljeffeg** [comment]
Made some additional changes - should hopefully work now.  Not sure what the `r9` is about.
