### ISSUE TITLE
Add support for Multi-Language Profiles

### ISSUE THREAD

**Issue by GuyKh** [eljeffeg/SmartCopy#97]
Today, when adding a source which the names language isn't English,
the created profiles is created with the names in the (default) English (in a separate language).

When creating/updating the profile, names should be added under the correct Language.

This can be done, by requesting field `names` from the API,
which will return the result - for example:

```
"profile-34773765351": {
    "id": "profile-34773765351",
    "public": true,
    "guid": "6000000173738984222",
    "first_name": "Yergis",
    "last_name": "Daugaviete",
    "name": "Yergis Daugaviete",
    "is_alive": false,
    "gender": "male",
    "names": {
        "en-US": {
            "first_name": "Yergis",
            "last_name": "Daugaviete"
        },
        "ru": {
            "first_name": "Йёргис",
            "last_name": "Даугавиетес"
        }
    },
    "deleted": false,
    ...
}
...
```

For input of new fields, we can use this:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/detectLanguage
for detecting which language is used.

**Comment by jeffg2k** [comment]
I tried out the `detectLanguage` and it was not reliable on names at all in my tests.  It would be nice to do, but without a good way to detect it and know if Geni supports it, it would be a challenge.

**Comment by GuyKh** [comment]
My thought was actually try to figure out if the names the user is trying to add/update are indeed in English or not.
If not - add/update to that language instead of English (default).

Many times I'm seeing stuff like this:
![image](https://user-images.githubusercontent.com/3136012/113508685-0a758000-955a-11eb-9c9f-f9afce05f8d8.png)

Where the Hebrew name exists, only under the Hebrew language **in addition to English transcription**

**Comment by jeffg2k** [comment]
Adding a select for the language and submitting it as a particular language is doable.  The harder challenge comes with the Geni side for comparing.  As when you change the selection, we'd probably want to also show what is listed on Geni for that language.  So just need to parse those values and update on change, and repeat for all family members.

<img width="475" alt="Screen Shot 2021-04-04 at 11 32 55 AM" src="https://user-images.githubusercontent.com/161904/113513837-86130500-9539-11eb-936b-58ad5fb0d50c.png">

**Comment by GuyKh** [comment]
Yeah, that's not trivial indeed. Yet, I think this should be added

**Comment by jeffg2k** [comment]
Pushed an update that tries to implement this.  It should work on "title", "first_name", "middle_name", "last_name", "maiden_name", "suffix", and "display_name".  The only name field it doesn't work is "nicknames" (Also Known As) as there is more involved with appending existing names and such.
